meta: [
      { charSet: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      { title: "ScanVirusDZ — Instant URL & File Threat Scanner" },
      { name: "description", content: "Scan any URL or file with 70+ antivirus engines via VirusTotal." },
      { property: "og:title", content: "ScanVirusDZ" },
      { property: "og:description", content: "Instant URL & File Threat Scanner powered by VirusTotal." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary" },
    ],
